
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */

public class Main : SEScene
{
	SESprite bg;
	SESprite bg2;
	
	public void initialize(SEResourceCache rsc)
	{
		base.initialize(rsc);
		bg = add_sprite_for_color(Color.instance("black"), get_scene_width(), get_scene_height());
		bg.move(0,0);
		bg2 = add_sprite_for_color(Color.instance("white"), 100, 100);
		bg2.move(900,500);
	}
	
}
